### ISSUE TITLE
\usepackage{ubuntu} did not work on beamer? 

### ISSUE THREAD

**Issue by raden** [tzwenn/ubuntu-latex-fonts#7]
Hi,

I issued \usepackage[regular]{ubuntu} on my preamble, seems it does not change the characters/words' font automatically.

Instead, I have to invoke \fontUbuntu{whatever} for the intended words.

I this case I'm using beamer package

**Comment by tzwenn** [comment]
Hi radon, thanks for this message.

Beamer overwrites the default fontfamily to be \sfdefault. The Ubuntufont redefines the standard roman (serif) font. Therefore you don't see the changes. 

For some reasons providing this package as non-serif font works well Mac OS X but fails on my Ubuntu installation. As long as I haven't pushed yet put a single \fontUbuntu right after the \begin{document} which will do most of the job.

**Comment by raden** [comment]
Hi,

I tried also to create my own beamer theme:

http://codepad.org/5Uss6vhp

On Wed, Oct 19, 2011 at 3:08 PM, Sven Khler <
reply@reply.github.com>wrote:

> Hi radon, thanks for this message.
> 
> Beamer overwrites the default fontfamily to be \sfdefault. The Ubuntufont
> redefines the standard roman (serif) font. Therefore you don't see the
> changes.
> 
> For some reasons providing this package as non-serif font works well Mac OS
> X but fails on my Ubuntu installation. As long as I haven't pushed yet put a
> single \fontUbuntu right after the \begin{document} which will do most of
> the job.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tzwenn/ubuntu-latex-fonts/issues/7#issuecomment-2452709

## 

https://sites.google.com/site/najmizabidi/

**Comment by rvf0068** [comment]
You could also say:

```
\renewcommand{\sfdefault}{ubuntu}
```
